// <auto-generated />
namespace ProSwap.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addedposts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedposts));
        
        string IMigrationMetadata.Id
        {
            get { return "202007231500176_added-posts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
